# --- PostgreSQL (Render, EXTERNO + SSL) ---
# application.properties
spring.datasource.url=jdbc:postgresql://dpg-d3ha9bali9vc73dvlf6g-a.oregon-postgres.render.com:5432/db_connected?sslmode=require
spring.datasource.username=admin
spring.datasource.password=5VsAcBHxsevPUE2rDx6dWhyMi1by5Vzr
spring.datasource.driver-class-name=org.postgresql.Driver


# --- Refuerzo SSL vía Hikari (por si el param no se aplica) ---
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.ssl=true

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# --- Hikari ---
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# --- Inicialización SQL (si usas data.sql) ---
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# --- JWT ---
jwt.secret=p4t0-ULTRA-SECRET0-m1n1m0-64-caracteres-para-HS512-1234567890abcdEFGHIJKLmnoPQRS
jwt.expiration=86400000   # 24h en milisegundos (ajusta si tu código lo usa)


